CREATE DATABASE IO_TEST;
USE IO_TEST;
CREATE TABLE IF NOT EXISTS Users (Pseudo VARCHAR(30), mdp VARCHAR(60), mail VARCHAR(30)), birthdate VARCHAR(10));
CREATE TABLE IF NOT EXISTS Publications (nom VARCHAR(50), description TEXT, type VARCHAR(10), size FLOAT, auteur VARCHAR(30), date VARCHAR(10));